apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::476466687708:role/eksctl-myproject04eksctl-nodegrou-NodeInstanceRole-B5SFXL49CY5X
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::476466687708:role/UdacityFlaskDeployCBKubectlRole
      username: build     
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-25T04:23:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1204"
  uid: 51ab1104-5c92-4e17-a02e-fbf491e5bd2b
